export const styles = {
  wrapper: {
    left: "auto",
    right: "auto",
    width: "100%",
    background: "#18181899",
    color: "black",
    opacity: "0,5",
    height: "100%",
    display: "flex",
    alignItems: "start",
    minHeight: "1000px",
  },
  window: {
    borderRadius: 5,
    padding: 60,
    display: "flex",
    marginTop: 0,
    marginLeft: "auto",
    marginRight: "auto",
    boxShadow: "2px 2px 10px rgba(90, 87, 87, 0.3)",
    zIndex: 10,
    minWidth: 350,
    minHeight: 80,
  },
};
